// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABQe8JkpxsioVLOc-5oUvvJNNbr_rSmz8',
    appId: '1:916420932623:web:f4cb7c26edeff4a47b1f7a',
    messagingSenderId: '916420932623',
    projectId: 'taskapp-5c1f0',
    authDomain: 'taskapp-5c1f0.firebaseapp.com',
    storageBucket: 'taskapp-5c1f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3Ay9UWDEubenvfjD976S7M2rP6t-0_k',
    appId: '1:916420932623:android:fe2b7a76366fd86d7b1f7a',
    messagingSenderId: '916420932623',
    projectId: 'taskapp-5c1f0',
    storageBucket: 'taskapp-5c1f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlFwYxVkQtNlO3dmVpZr6ZWPbS08QrQJs',
    appId: '1:916420932623:ios:5db5f3de62cebc807b1f7a',
    messagingSenderId: '916420932623',
    projectId: 'taskapp-5c1f0',
    storageBucket: 'taskapp-5c1f0.firebasestorage.app',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlFwYxVkQtNlO3dmVpZr6ZWPbS08QrQJs',
    appId: '1:916420932623:ios:5db5f3de62cebc807b1f7a',
    messagingSenderId: '916420932623',
    projectId: 'taskapp-5c1f0',
    storageBucket: 'taskapp-5c1f0.firebasestorage.app',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABQe8JkpxsioVLOc-5oUvvJNNbr_rSmz8',
    appId: '1:916420932623:web:f06c2e21d9c46ae97b1f7a',
    messagingSenderId: '916420932623',
    projectId: 'taskapp-5c1f0',
    authDomain: 'taskapp-5c1f0.firebaseapp.com',
    storageBucket: 'taskapp-5c1f0.firebasestorage.app',
  );
}
